CREATE TABLE IF NOT EXISTS profile (
	id VARCHAR(999) PRIMARY KEY,
	key VARCHAR(999)
);
CREATE TABLE IF NOT EXISTS user (
	id int PRIMARY KEY,
	name VARCHAR(999),
	email VARCHAR(999),
	profile_id VARCHAR(999) FOREIGN KEY REFERENCES profile (id)
);