name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package

      - name: Coverage upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/jacoco.exec
          flags: all
          fail_ci_if_error: true

      - name: Deploy SNAPSHOT
        if: github.ref == 'refs/heads/master'
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${OSSRH_USER}</username><password>${OSSRH_PASS}</password></server></servers></settings>" > deploy-settings.xml
          mvn deploy -DskipTests -Dgpg.skip --settings deploy-settings.xml
